// Generated by CoffeeScript 1.6.3
(function() {
  var Confirm, Dialog, Overlay, Q, dialog;

  Dialog = require('Dialog');

  Confirm = require('ConfirmDialog');

  Overlay = require('overlay');

  Q = require('q');

  Q.stopUnhandledRejectionTracking();

  dialog = null;

  describe('ConfirmDialog', function() {
    beforeEach(function() {
      return dialog = new Confirm;
    });
    afterEach(function() {
      if (Overlay.el) {
        Overlay.el.remove();
        Overlay.el = null;
      }
      if (dialog.el) {
        dialog.el.remove();
        dialog.el = null;
      }
      Overlay.visible = false;
      Dialog.visible = null;
      return Dialog.closing = false;
    });
    describe('#constructor()', function() {
      return it('should create base two buttons', function() {
        return expect(dialog.buttons.length).to.be.equal(2);
      });
    });
    describe('#onTrue()', function() {
      return it('should call this method when ok button is clicked', function(done) {
        dialog.onTrue(function() {
          return done();
        });
        return dialog.show().then(function() {
          var button;
          button = $(dialog.el).find('div.buttons a:nth-child(1)');
          return button.click();
        }).done();
      });
    });
    return describe('#onFalse()', function() {
      return it('should call this method when cancel button is clicked', function(done) {
        dialog.onFalse(function() {
          return done();
        });
        return dialog.show().then(function() {
          var button;
          button = $(dialog.el).find('div.buttons a:nth-child(2)');
          return button.click();
        }).done();
      });
    });
  });

}).call(this);
