// Generated by CoffeeScript 1.6.3
(function() {
  var ConfirmDialog, Dialog,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Dialog = require('./Dialog');

  ConfirmDialog = (function(_super) {
    __extends(ConfirmDialog, _super);

    ConfirmDialog.trueText = 'OK';

    ConfirmDialog.falseText = 'Cancel';

    ConfirmDialog.prototype.trueText = null;

    ConfirmDialog.prototype.falseText = null;

    function ConfirmDialog(jquery, content, trueText, falseText) {
      var _this = this;
      this.content = content;
      this.trueText = trueText != null ? trueText : ConfirmDialog.trueText;
      this.falseText = falseText != null ? falseText : ConfirmDialog.falseText;
      ConfirmDialog.__super__.constructor.call(this, jquery);
      this.addButton(this.trueText, function() {
        return _this.emit('true', _this);
      });
      this.addButton(this.falseText, function() {
        return _this.emit('false', _this);
      });
    }

    return ConfirmDialog;

  })(Dialog);

  module.exports = ConfirmDialog;

}).call(this);
